repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json, toml]
  - repo: local
    hooks:
      - id: audit-python
        name: audit-python
        entry: pixi run audit-python
        language: system
        pass_filenames: false
        always_run: true
      - id: audit-rust
        name: audit-rust
        entry: pixi run audit-rust
        language: system
        pass_filenames: false
        always_run: true
