services:
  pocket-tts:
    image: "pocket-tts:latest"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pocket-tts
    command:
      - "--host"
      - "${HOST:-0.0.0.0}"
      - "--port"
      - "${PORT:-8000}"
    env_file:
      - .env
    ports:
      - "8000:${PORT:-8000}"
    volumes:
      - ${CACHE_LOCATION}:/root/.cache
